/* Referências Cavan dos cinco relatórios Excel fornecidos em 08/09/2026.
   Cargas são forças em kN; momentos de projeto permanecem em kN·m.
   Divergências de fonte são explícitas e não viram limites automáticos. */
const ESPEC_CAVAN = (() => {
  const revisao = 'Cavan — relatórios Excel recebidos em 08/09/2026';
  const comuns = {
    revisao_fonte: revisao,
    slump_abatimento_inicio: '230 ±30 mm (200 a 260 mm)',
    slump_abatimento_meio: '230 ±30 mm (200 a 260 mm)',
    slump_abatimento_fim: '230 ±30 mm (200 a 260 mm)',
    slump_espalhamento_inicio: '400 a 600 mm',
    slump_espalhamento_meio: '400 a 600 mm',
    slump_espalhamento_fim: '400 a 600 mm',
    desprotensao: 'Mínimo não informado nos anexos; confirmar requisito aplicável.',
    comp_axial_3_dias: 'Mínimo não informado no anexo.',
    comp_axial_7_dias: 'Mínimo não informado no anexo.',
    comp_axial_14_dias: 'Mínimo não informado no anexo.',
    comp_axial_28_dias: 'Mínimo não informado no anexo.',
    tracao_flexao_7_dias: 'Mínimo não informado no anexo.',
    tracao_flexao_14_dias: 'Mínimo não informado no anexo.',
    tracao_flexao_28_dias: 'Mínimo não informado no anexo.',
    idades_ensaios_concreto: 'DOCUMENTAL C58:C62: compressão aos 3 ou 7, 7 ou 14 e 28 dias; flexão aos 7 ou 14 e 28 dias. Definir a idade aplicável ao lote.',
    fissura_apoio_positivo: 'Não deve apresentar fissuras.',
    fissura_apoio_negativo: 'Não deve apresentar fissuras.',
    fissura_centro_positivo: 'Não deve apresentar fissuras.',
    fissura_centro_negativo: 'Não deve apresentar fissuras.',
    ancoragem_fissura_descarga: 'Não deve haver fissura maior que 0,5 mm após descarregamento.',
    ensaio_ruina: 'Após aderência, zerar a carga e retirar os relógios; carga de ruína superior à de ancoragem. Sem limite superior especificado.',
    verificacao_trincas_ombreira: 'Inspecionar trincas com lupa após os ensaios.',
    inclinacao_base_apoio_trilhos: '1:35 a 1:45 — ESTRUTURAL C12.',
    leitura_gabarito_inclinacao: 'Cavan: 2,22 a 2,85, conforme N12. Unidade e calibração do gabarito a confirmar.',
    empeno_transversal_entre_apoios: '≤1 mm — Cavan; ESTRUTURAL C13/N13.',
    comprimento_dormente: 'Nominal 2800 mm; ±6 mm (2794 a 2806 mm).',
    superficie_apoio_trilho: 'Plana e lisa; irregularidades de até 1 mm, conforme ficha estrutural.',
    bitola_grade_montada: '1600 mm +2/−1 mm (1599 a 1602 mm); pré-montagem ou grade com pelo menos 10 dormentes — ESTRUTURAL C11/N11.',
    temperatura_maxima: '≤60 °C. Reduzir se SO3 do cimento >2%; novo teto não informado na ficha.',
    temperatura_inicial_concretagem: '≤30 °C.',
    diferenca_temperatura_nucleo_superficie: 'Confirmar fronteira: descrição exige <20 °C; a coluna de tolerância de algumas fichas informa ≤20 °C.',
    taxa_aquecimento_cura: 'Máximo 20 °C/h, em todas as horas.',
    monitoramento_cura: 'Registrar curva; medir próximo da profundidade e largura médias do dormente. Cobrir moldes com manta térmica umedecida após concretagem.',
    peso_total_com_insumos: '400 kg na ficha; peso total com insumos. Confirmar se é máximo ou referência nominal.',
    armazenamento_acondicionamento: 'Terreno plano; barrotes nos apoios dos trilhos; peças na horizontal com face superior para cima; pilhas do mesmo lote identificadas; espaço mínimo entre pilhas de 0,80 m.',
    documental_agregado_miudo: 'DOCUMENTAL N11:N22: finos na peneira 75 µm ≤3%; densidade seca 2,10 a 2,60 g/cm³; absorção ≤1%; massa unitária solta 1300 a 1600 kg/m³; vazios 35 a 55%; argila e friáveis total ≤3%. Faixas ≥1,18/<4,75 mm e ≥4,75/<9,5 mm identificam frações granulométricas, não teor admissível. Demais mínimos/máximos não preenchidos.',
    documental_agregado_graudo: 'DOCUMENTAL N24:N37: finos na peneira 75 µm ≤1%; densidade seca 2,60 a 2,95 g/cm³; absorção ≤1%; massa unitária solta 1410 a 1550 kg/m³; vazios 40 a 55%; argila e friáveis total ≤2%; Los Angeles <50 (escala/unidade a confirmar). Índice de forma escrito ≤3,0%: confirmar unidade antes de adotar. Demais mínimos/máximos não preenchidos.',
    documental_aco: 'DOCUMENTAL N40:N41: relaxação em 1000 h: 3% (valor 0,03, formato percentual; desigualdade não explicitada); diâmetro 6 ±0,5 mm. Conferir laudo de propriedades físicas e mecânicas.',
    documental_cimento: 'DOCUMENTAL N44:N55: perda ao fogo ≤6,5%; SO3 ≤4,5%; resíduo insolúvel ≤3,5%; MgO ≤6,5%; compressão do CIMENTO: 1 dia ≥14 MPa, 3 dias ≥24 MPa, 7 dias ≥34 MPa; 28 dias marcado não aplicável; pega ≥60 min; finura #200 ≤6%. A/C sem limite preenchido. Estes valores não são resistências do concreto do dormente.',
    documental_concreto: 'DOCUMENTAL C57:C68: laudos de adições, compressão, flexão, abatimento, reatividade álcali-agregado, análise petrográfica, mitigação, potencial DEF e água de preparo. As células N58:N62 não informam mínimos de resistência do concreto.',
  };
  const usp = {
    usp_distancia_bordos: '≥10 e ≤20 mm dos bordos da face inferior.',
    usp_imersao_elastomero: '≥2 mm no concreto fresco, além da camada de conexão.',
    usp_espessura_elastomero_externo: '≥7 e ≤20 mm.',
    usp_planicidade: '≤2 mm na peça de 1380 mm — referência mantida EM-SPE-055 rev.05.',
    usp_rigidez_estatica: 'Cstat ≥0,22 N/mm³ — NBR 16649 Anexo A, categoria C; referência mantida EM-SPE-055 rev.05.',
    usp_area_contato: '≥18% — NBR 16649 Anexo C; referência mantida EM-SPE-055 rev.05.',
    usp_resistencia_arrancamento: '≥0,3 N/mm² — NBR 16649; ficha estrutural e EM-SPE-055 rev.05.',
    usp_resistencia_tracao: '≥2,5 N/mm² — NBR 16649 Anexo F; referência mantida EM-SPE-055 rev.05.',
    usp_carga_arrancamento: '58,90 kgf na ficha. Confirmar área/diâmetro do corpo de prova; não converter diretamente esta carga em tensão sem a área.',
  };
  const geometriaRetangular = {
    base_retangular: 'Nominal 265 mm; ±3 mm (262 a 268 mm).',
    altura_secao_plataforma: 'Nominal 240 mm; +6/−3 mm (237 a 246 mm).',
    altura_secao_centro: 'Nominal 200 mm; +6/−3 mm (197 a 206 mm).',
    altura_ombreira: 'Pendente: texto menciona ±2,00 mm; célula de tolerância traz sinais incoerentes (<−2,00 ou <2,00). Confirmar critério do relógio comparador.',
  };
  const geometriaVariavel = {
    largura_base_apoio: 'Nominal 300 mm; ±3 mm (297 a 303 mm).',
    largura_base_centro: 'Nominal 240 mm; ±3 mm (237 a 243 mm).',
    altura_secao_plataforma: 'Nominal 250 mm; +6/−3 mm (247 a 256 mm).',
    altura_secao_centro: 'Nominal 220 mm; +6/−3 mm (217 a 226 mm).',
    altura_ombreira: 'Verificação por gabarito; tolerância numérica não informada na ficha.',
  };
  const posicionamento = 'Vertical ±3 mm; horizontal ±6 mm — conforme projeto.';
  const pendenciasComuns = 'Confirmar unidade/calibração da leitura do gabarito, definição do peso total, redução da temperatura de cura quando SO3 >2% e unidades/fronteiras documentais indicadas como pendentes. Valores não informados não equivalem a zero.';

  const projetos = [
    {
      projeto: 'MALHA PAULISTA BITOLA MISTA', bitola: 'Bitola Mista', tipo_dormente: 'Bitola Mista MP - USP',
      ...geometriaRetangular, ...usp,
      arquivo: 'Lt  Relatório inspeção - Cavan --26 - Mista.xlsx',
      linhas: 'Dimensional C11:N22; cargas C24:N33; produção C36:N49.',
      desenho_referencia: 'Aba intitulada Desenho ENG-DVP-D130; desenho incorporado com base de 264 mm. Confirmar identificação/revisão do desenho para Mista.',
      cargas: ['256,54', '191,08', '53,50', '76,43', '384,81'], arrancamento: '53,88', apoios: ['a','b','c'],
      aderencia_escorregamento_aco: 'Referência 0,025 mm; ficha sem desigualdade explícita. Confirmar fronteira de aceitação.',
      base_retangular: 'Pendente de confirmação: ficha 265 ±3 mm; desenho incorporado cota 264 mm.',
      altura_secao_plataforma: 'Ficha: nominal 250 mm; +6/−3 mm (247 a 256 mm).',
      altura_secao_centro: 'Ficha: nominal 225 mm; +6/−3 mm (222 a 231 mm). Confirmar seção correspondente no desenho incorporado.',
      distancia_apoio_centro: 'Centro da região do trilho ao centro do dormente: 839,6 ±12 mm.',
      ombreiras_externas_mesa: 'Nominal da ficha 1850,00 mm — mesa (W/X). Tolerância pendente.',
      ombreiras_externas_faces: 'Nominal da ficha 1850,55 mm — faces (A/B). Tolerância pendente.',
      ombreiras_locais_mesa: 'Nominal da ficha 170,80 ±1 mm (169,80 a 171,80 mm) — mesa (W/X); confirmar divergência de tolerância com desenho.',
      ombreiras_locais_faces: 'Nominal da ficha 171,85 ±1 mm (170,85 a 172,85 mm) — faces (A/B); confirmar desenho.',
      tolerancias_ombreiras: 'Externas: C19 informa −1,5/+0,5 mm; N19 fornece extremos equivalentes a −0,5/+1,5 mm. Não usar os sinais <... >... como faixa válida. Locais: C20/N20 informa ±1 mm; desenho apresenta outra tolerância. Confirmar revisão e pontos.',
      quantidade_fios_protensao: '18 fios — ESTRUTURAL C22.', posicionamento_fios_protensao: posicionamento,
      peso_total_com_insumos: '440 kg na ficha; peso total com insumos. Confirmar se é máximo ou referência nominal.',
      bitola_grade_montada: 'Ficha N11: 1600 mm +2/−1 mm para a via larga; bitola adicional da via mista não especificada na ficha. Confirmar critério específico.',
      comp_axial_14_dias: null, tracao_flexao_14_dias: null,
      idades_ensaios_concreto: 'DOCUMENTAL C58:C62: compressão aos 3, 7 e 28 dias; flexão aos 7 e 28 dias. Mínimos não preenchidos.',
      pendencias_confirmacao: 'Base: ficha 265 mm × desenho 264 mm; altura central e seção correspondente; tolerâncias das ombreiras externas/locais; sinais na altura da ombreira; bitola adicional da Mista. ' + pendenciasComuns,
    },
    {
      projeto: 'MALHA PAULISTA BITOLA LARGA', bitola: 'Bitola Larga', tipo_dormente: 'Bitola Larga MP',
      ...geometriaRetangular, ...usp,
      arquivo: 'Lt  Relatório inspeção - Cavan --2026 - Larga MP.xlsx',
      linhas: 'Dimensional C11:N22; cargas C24:N33; produção C36:N49.',
      desenho_referencia: 'ENG-DVP-D130 — desenho incorporado ao anexo MP.',
      cargas: ['193,94', '144,43', '44,76', '63,87', '290,91'], arrancamento: '53,88', apoios: ['a','b'],
      aderencia_escorregamento_aco: 'Referência 0,025 mm; ficha sem desigualdade explícita. Confirmar fronteira de aceitação.',
      distancia_apoio_centro: 'Centro da região do trilho ao centro do dormente: 839,6 ±12 mm.',
      ombreiras_externas_mesa: 'Nominal da ficha 1850,00 mm — mesa (W/X). Tolerância pendente.',
      ombreiras_externas_faces: 'Nominal da ficha 1850,55 mm — faces (A/B). Tolerância pendente.',
      ombreiras_locais_mesa: 'Nominal da ficha 170,80 ±1 mm (169,80 a 171,80 mm) — mesa (W/X); confirmar divergência com desenho.',
      ombreiras_locais_faces: 'Nominal da ficha 171,85 ±1 mm (170,85 a 172,85 mm) — faces (A/B); confirmar desenho.',
      tolerancias_ombreiras: 'Externas: C19 informa −1,5/+0,5 mm; N19 fornece extremos equivalentes a −0,5/+1,5 mm. Locais: ficha ±1 mm × detalhe do desenho −0,5/+1,5 mm. Confirmar referência antes de adotar uma faixa.',
      quantidade_fios_protensao: '15 fios — ESTRUTURAL C22.', posicionamento_fios_protensao: posicionamento,
      carga_eixo_projeto: '32,5 t/eixo', velocidade_maxima_projeto: '80 km/h',
      espacamento_dormentes: 'Máx. 600 mm (1.667 dormentes/km)',
      peso_maximo_dormente: '≤400 kg excluindo fixações — referência mantida EM-SPE-035 rev.10; distinta do peso total da ficha.',
      inclinacao_trilho: '1:40, para dentro da via', pressao_max_lastro: '≤1,00 MPa',
      dist_centro_eixo_via: 'Tolerância 12 mm (controle na forma) — referência mantida EM-SPE-035 rev.10.',
      momento_fletor_positivo_apoio: '30,6 kN·m', momento_fletor_negativo_apoio: '21,4 kN·m',
      momento_fletor_negativo_centro: '24,4 kN·m', momento_fletor_positivo_centro: '17,1 kN·m',
      fio_protensao: 'CP 170 RB ou CP 175 RB (NBR 7482); aderência inicial exige acabamento entalhado E.',
      danos_admissiveis_movimentacao: '≤10 mm prof. × ≤150 mm compr. × ≤25 mm alt., só abaixo da linha de centro; armadura exposta = refugo — referência mantida EM-SPE-035 rev.10.',
      comp_axial_28_dias: '≥65 MPa — referência mantida EM-SPE-035 rev.10; anexo sem mínimo preenchido.',
      tracao_flexao_28_dias: '≥7,5 MPa — referência mantida EM-SPE-035 rev.10; anexo sem mínimo preenchido.',
      pendencias_confirmacao: 'Tolerâncias das ombreiras externas/locais; sinais na altura da ombreira; 400 kg com insumos na ficha × limite de 400 kg excluindo fixações na referência anterior. ' + pendenciasComuns,
    },
    {
      projeto: 'FERRO NORTE', bitola: 'Bitola Larga', tipo_dormente: 'Bitola Larga FN', ...geometriaVariavel,
      arquivo: 'Lt  Relatório inspeção - Cavan --2026 - Larga FN.xlsx',
      linhas: 'Dimensional C11:N23; cargas C25:N33; produção C36:N48.',
      desenho_referencia: 'ENG-DVP-D029 — desenho incorporado indica inclinação 1:20.',
      cargas: ['234,75', '174,95', '46,84', '66,91', '352,13'], arrancamento: '53,38', apoios: ['a','b'],
      aderencia_escorregamento_aco: '≤0,025 mm — ESTRUTURAL N30.',
      inclinacao_base_apoio_trilhos: 'Pendente: ficha C12 exige 1:35 a 1:45; desenho ENG-DVP-D029 indica 1:20. Confirmar projeto/revisão.',
      leitura_gabarito_inclinacao: 'Cavan FN: 4,54 a 5,55 conforme N12; confirmar unidade, gabarito e sua relação com a inclinação de projeto.',
      distancia_apoio_centro: 'Centro da região do trilho ao centro do dormente: 844,02 ±12 mm.',
      ombreiras_externas_mesa: 'Nominal 1842,53 mm; −0,5/+1,5 mm (1842,03 a 1844,03 mm), conforme descrição da ficha; confirmar pontos no desenho.',
      ombreiras_externas_faces: 'Nominal 1842,58 mm; −0,5/+1,5 mm (1842,08 a 1844,08 mm), conforme descrição da ficha; confirmar pontos no desenho.',
      ombreiras_locais_mesa: 'Nominal 154,50 mm; −0,5/+1,5 mm (154,00 a 156,00 mm), conforme descrição da ficha; confirmar divergência com desenho.',
      ombreiras_locais_faces: 'Nominal 155,55 mm; −0,5/+1,5 mm (155,05 a 157,05 mm), conforme descrição da ficha; confirmar desenho.',
      tolerancias_ombreiras: 'C20:C21 especifica −0,5/+1,5 mm. N20:N21 usa sinais <... >... incoerentes como faixa. O desenho mostra cotas distintas; confirmar correspondência dos pontos de medição antes da aceitação.',
      quantidade_fios_protensao: '16 fios — ESTRUTURAL C23.', posicionamento_fios_protensao: posicionamento,
      pendencias_confirmacao: 'Inclinação: 1:35 a 1:45 na ficha × 1:20 no desenho; cotas do desenho versus pontos mesa/face da ficha; altura da ombreira sem tolerância numérica. ' + pendenciasComuns,
    },
    {
      projeto: 'FMT', bitola: 'Bitola Larga', tipo_dormente: 'Bitola Larga FMT USP', ...geometriaRetangular, ...usp,
      arquivo: 'Lt  Relatório inspeção - Cavan --2026 - Larga FMT.xlsx',
      linhas: 'Dimensional C11:N20; cargas C22:N31; produção C34:N47.',
      desenho_referencia: 'ENG-DVP-D205 — desenho incorporado ao anexo FMT (substitui a referência D130 do modelo anterior).',
      cargas: ['193,47', '143,95', '44,76', '63,87', '290,21'], arrancamento: '53,38', apoios: ['a','b'],
      aderencia_escorregamento_aco: '<0,025 mm — ESTRUTURAL N27; diferença de fronteira em relação ao FN deve ser confirmada.',
      altura_secao_centro: 'Nominal 200 mm no desenho ENG-DVP-D205; tolerância central não informada na ficha. Confirmar revisão aplicável.',
      distancia_apoio_centro: 'Ficha C17/N17: distância interna da ombreira externa ao centro do dormente, 839,8 ±12 mm. Confirmar ponto: descrição difere das demais fichas.',
      ombreiras_externas_mesa: 'Nominal da ficha 1834,12 mm — mesa (W/X). Tolerância pendente.',
      ombreiras_externas_faces: 'Nominal da ficha 1834,67 mm — faces (A/B). Tolerância pendente.',
      ombreiras_locais_mesa: 'Nominal da ficha 154,50 mm — mesa (W/X). Tolerância pendente.',
      ombreiras_locais_faces: 'Nominal da ficha 155,55 mm — faces (A/B). Tolerância pendente.',
      tolerancias_ombreiras: 'C18:C19 informa −1,5/+0,5 mm; extremos de N18:N19 equivalem a −0,5/+1,5 mm. Confirmar antes de adotar faixas.',
      quantidade_fios_protensao: 'Não informada no quadro estrutural do anexo FMT.',
      temperatura_inicial_concretagem: '≤30 °C até a pega do concreto ou espera de 2 horas, o que for maior — C35.',
      diferenca_temperatura_nucleo_superficie: '<20 °C — ESTRUTURAL C36.',
      armazenamento_acondicionamento: 'Terreno plano; barrotes nos apoios; peças na horizontal com face superior para cima; pilhas do mesmo lote identificadas. Ficha FMT C54: espaço mínimo 0,60 m (demais anexos: 0,80 m).',
      pendencias_confirmacao: 'Tolerâncias das ombreiras e sinais da altura da ombreira; ponto da distância de 839,8 mm; tolerância da altura central; fronteira <0,025 mm na aderência; espaço entre pilhas 0,60 m versus 0,80 m nas demais fichas. ' + pendenciasComuns,
    },
    {
      projeto: 'MALHA CENTRAL', bitola: 'Bitola Larga', tipo_dormente: 'Bitola Larga MC', ...geometriaVariavel,
      arquivo: 'Lt  Relatório inspeção - Cavan --26 - Larga MC.xlsx',
      linhas: 'Dimensional C11:N23; cargas C25:N33; produção C36:N48.',
      desenho_referencia: 'ENG-DVP-D141 — desenho incorporado ao anexo MC.',
      cargas: ['180,33', '134,28', '37,13', '53,04', '270,05'], arrancamento: '53,38', apoios: ['a','b'],
      aderencia_escorregamento_aco: 'Referência 0,025 mm; ficha sem desigualdade explícita. Confirmar fronteira de aceitação.',
      distancia_apoio_centro: 'Centro da região do trilho ao centro do dormente: 837,5 ±12 mm.',
      ombreiras_externas_mesa: 'Nominal 1829,23 mm; −0,5/+1,5 mm (1828,73 a 1830,73 mm), conforme descrição da ficha; confirmar desenho.',
      ombreiras_externas_faces: 'Nominal 1829,78 mm; −0,5/+1,5 mm (1829,28 a 1831,28 mm), conforme descrição da ficha; confirmar desenho.',
      ombreiras_locais_mesa: 'Nominal 157,70 mm; −0,5/+1,5 mm (157,20 a 159,20 mm), conforme descrição da ficha; confirmar desenho.',
      ombreiras_locais_faces: 'Nominal 158,75 mm; −0,5/+1,5 mm (158,25 a 160,25 mm), conforme descrição da ficha; confirmar desenho.',
      tolerancias_ombreiras: 'C20:C21 especifica −0,5/+1,5 mm; N20:N21 usa sinais <... >... incoerentes como faixa. Confirmar correspondência com os pontos cotados no desenho D141.',
      quantidade_fios_protensao: '12 fios — ESTRUTURAL C23.', posicionamento_fios_protensao: posicionamento,
      pendencias_confirmacao: 'Pontos de medição das ombreiras e sinais de faixa; altura da ombreira sem tolerância numérica. ' + pendenciasComuns,
    },
  ];
  const chavesCargas = ['momento_positivo_apoio_trilho', 'momento_negativo_apoio_trilho', 'momento_positivo_centro', 'momento_negativo_centro', 'ancoragem'];
  const padroes = Object.fromEntries(projetos.map(({ arquivo, linhas, cargas, arrancamento, apoios, ...projeto }) => {
    const r = { ...comuns, ...projeto };
    chavesCargas.forEach((chave, i) => { r[chave] = `${cargas[i]} kN — ${i === 4 ? 'sem fissura >0,5 mm após descarga' : 'sem fissuras'}`; });
    apoios.forEach(apoio => {
      r[`arrancamento_ombreira_${apoio}`] = `${arrancamento} kN — carga da ficha.`;
      r[`torcao_ombreira_${apoio}`] = '340 N·m — carga de ensaio; verificar trincas.';
    });
    r.fonte_documental = `${arquivo} — ESTRUTURAL: ${linhas} DOCUMENTAL C11:N68. DOCUMENTAL (old) não utilizada para substituir limites.`;
    r.observacao = 'Referência consultiva Cavan. Cargas e nominais transcritos do anexo; divergências sinalizadas para confirmação. Não contém resultados medidos de lotes. Parâmetros normativos anteriores identificados foram preservados quando o anexo não os substitui.';
    return [r.projeto, r];
  }));
  return { revisao, padroes };
})();
