// Ordem das colunas de cada aba da planilha Controle_Semanal_CONPREM.xlsx.
//
// Esta é a fonte da verdade do projeto: o xlsx exportado sai exatamente nesta
// sequência, para que o conteúdo possa ser copiado e colado direto na planilha
// de controle sem reordenar nada. Se a planilha mudar, mude aqui.
//
// tipo:
//   'texto'  -> célula de texto (preserva zeros à esquerda de NF/certificado)
//   'numero' -> célula numérica
//   'data'   -> data real do Excel, formatada dd/mm/aaaa

export const MODELOS = {
  rastreabilidade: {
    id: 'rastreabilidade',
    aba: 'Rastreabilidade',
    rotulo: 'Mapa de Rastreabilidade',
    descricao: 'Um lote por linha, com sequenciais e certificados de cada insumo.',
    colunas: [
      { chave: 'semana', titulo: 'Semana', tipo: 'texto' },
      { chave: 'ordemFabricacao', titulo: 'Ordem de fabricação', tipo: 'texto' },
      { chave: 'pedido', titulo: 'Pedido', tipo: 'texto' },
      { chave: 'cliente', titulo: 'Cliente', tipo: 'texto' },
      { chave: 'produto', titulo: 'Produto', tipo: 'texto' },
      { chave: 'lote', titulo: 'Lote', tipo: 'texto' },
      { chave: 'dataFabricacao', titulo: 'Data fabricação', tipo: 'data' },
      { chave: 'qtdDormentes', titulo: 'Qtd. dormentes', tipo: 'numero' },
      { chave: 'serieConcreto', titulo: 'Série concreto', tipo: 'texto' },
      { chave: 'acoSeqNf', titulo: 'Aço - Seq./NF', tipo: 'texto' },
      { chave: 'acoCertInterno', titulo: 'Aço - Cert. interno', tipo: 'texto' },
      { chave: 'acoCertExterno', titulo: 'Aço - Cert. externo', tipo: 'texto' },
      { chave: 'cimentoSeqNf', titulo: 'Cimento - Seq./NF', tipo: 'texto' },
      { chave: 'cimentoCertInterno', titulo: 'Cimento - Cert. interno', tipo: 'texto' },
      { chave: 'cimentoCertExterno', titulo: 'Cimento - Cert. externo', tipo: 'texto' },
      { chave: 'areiaSeqNf', titulo: 'Areia - Seq./NF', tipo: 'texto' },
      { chave: 'areiaCertInterno', titulo: 'Areia - Cert. interno', tipo: 'texto' },
      { chave: 'areiaCertExterno', titulo: 'Areia - Cert. externo', tipo: 'texto' },
      { chave: 'britaSeqNf', titulo: 'Brita - Seq./NF', tipo: 'texto' },
      { chave: 'britaCertInterno', titulo: 'Brita - Cert. interno', tipo: 'texto' },
      { chave: 'britaCertExterno', titulo: 'Brita - Cert. externo', tipo: 'texto' },
      { chave: 'aditivoSeqNf', titulo: 'Aditivo - Seq./NF', tipo: 'texto' },
      { chave: 'aditivoCertExterno', titulo: 'Aditivo - Cert. externo', tipo: 'texto' },
      { chave: 'adicaoSeqNf', titulo: 'Adição - Seq./NF', tipo: 'texto' },
      { chave: 'adicaoCertExterno', titulo: 'Adição - Cert. externo', tipo: 'texto' },
      { chave: 'ombreiraLote', titulo: 'Ombreira - lote', tipo: 'texto' },
      { chave: 'grampo', titulo: 'Grampo', tipo: 'texto' },
      { chave: 'isoladorFrontal', titulo: 'Isolador frontal', tipo: 'texto' },
      { chave: 'isoladorLateral', titulo: 'Isolador lateral', tipo: 'texto' },
      { chave: 'palmilhaTrilho', titulo: 'Palmilha trilho', tipo: 'texto' },
      { chave: 'palmilhaUsp', titulo: 'Palmilha USP', tipo: 'texto' },
      { chave: 'observacoes', titulo: 'Observações', tipo: 'texto' },
    ],
  },

  ensaios: {
    id: 'ensaios',
    aba: 'Ensaios',
    rotulo: 'Ensaio de Dormentes',
    descricao: 'Um lote ensaiado por linha. No PDF os lotes vêm em colunas.',
    colunas: [
      { chave: 'semana', titulo: 'Semana', tipo: 'texto' },
      { chave: 'ordemFabricacao', titulo: 'OF', tipo: 'texto' },
      { chave: 'pedido', titulo: 'Pedido', tipo: 'texto' },
      { chave: 'cliente', titulo: 'Cliente', tipo: 'texto' },
      { chave: 'lote', titulo: 'Lote', tipo: 'texto' },
      { chave: 'dataFabricacao', titulo: 'Data fabricação', tipo: 'data' },
      { chave: 'turno', titulo: 'Turno', tipo: 'texto' },
      { chave: 'dataEnsaio', titulo: 'Data ensaio', tipo: 'data' },
      { chave: 'pista', titulo: 'Pista', tipo: 'numero' },
      { chave: 'molde', titulo: 'Molde', tipo: 'numero' },
      { chave: 'linha', titulo: 'Linha', tipo: 'numero' },
      { chave: 'medExtPassa', titulo: 'Medida externa - passa', tipo: 'texto' },
      { chave: 'medExtNaoPassa', titulo: 'Medida externa - não passa', tipo: 'texto' },
      { chave: 'medIntPassa', titulo: 'Medida interna - passa', tipo: 'texto' },
      { chave: 'medIntNaoPassa', titulo: 'Medida interna - não passa', tipo: 'texto' },
      { chave: 'inclinacao1', titulo: 'Inclinação 1', tipo: 'texto' },
      { chave: 'inclinacao2', titulo: 'Inclinação 2', tipo: 'texto' },
      { chave: 'torcaoRelativa', titulo: 'Torção relativa', tipo: 'numero' },
      { chave: 'alturaOmbreira1', titulo: 'Altura ombreira 1', tipo: 'texto' },
      { chave: 'alturaOmbreira2', titulo: 'Altura ombreira 2', tipo: 'texto' },
      { chave: 'posicaoInsertos', titulo: 'Posição insertos', tipo: 'texto' },
      { chave: 'montagemFixacoes', titulo: 'Montagem fixações', tipo: 'texto' },
      { chave: 'comprimento', titulo: 'Comprimento mm', tipo: 'numero' },
      { chave: 'larguraApoioSup', titulo: 'Largura apoio sup. mm', tipo: 'numero' },
      { chave: 'larguraApoioInf', titulo: 'Largura apoio inf. mm', tipo: 'numero' },
      { chave: 'alturaApoio', titulo: 'Altura apoio mm', tipo: 'numero' },
      { chave: 'larguraCentroSup', titulo: 'Largura centro sup. mm', tipo: 'numero' },
      { chave: 'larguraCentroInf', titulo: 'Largura centro inf. mm', tipo: 'numero' },
      { chave: 'alturaCentro', titulo: 'Altura centro mm', tipo: 'numero' },
      { chave: 'momentoPosApoio', titulo: 'Momento + apoio', tipo: 'texto' },
      { chave: 'momentoNegApoio', titulo: 'Momento - apoio', tipo: 'texto' },
      { chave: 'momentoPosCentro', titulo: 'Momento + centro', tipo: 'texto' },
      { chave: 'momentoNegCentro', titulo: 'Momento - centro', tipo: 'texto' },
      { chave: 'arrancamentoOmbreiras', titulo: 'Arrancamento ombreiras', tipo: 'texto' },
      { chave: 'precargaUsp', titulo: 'Pré-carga USP kgf', tipo: 'numero' },
      { chave: 'cargaMaxUsp', titulo: 'Carga máx. USP kgf', tipo: 'numero' },
      { chave: 'resultadoUsp', titulo: 'Resultado USP', tipo: 'texto' },
      { chave: 'torcaoOmbreiras', titulo: 'Torção ombreiras', tipo: 'texto' },
      { chave: 'aderenciaCargaFinal', titulo: 'Aderência/carga final', tipo: 'texto' },
      { chave: 'bitola', titulo: 'Bitola', tipo: 'texto' },
      { chave: 'executor', titulo: 'Executor', tipo: 'texto' },
      { chave: 'relatorioFotografico', titulo: 'Relatório fotográfico', tipo: 'texto' },
      { chave: 'fiscalizacao', titulo: 'Fiscalização', tipo: 'texto' },
      { chave: 'resultadoGeral', titulo: 'Resultado geral', tipo: 'texto' },
      { chave: 'observacoes', titulo: 'Observações', tipo: 'texto' },
    ],
  },

  resumo: {
    id: 'resumo',
    aba: 'Resumo Semanal',
    rotulo: 'Resumo Semanal (produção e refugos)',
    descricao: 'Uma linha por semana, com refugos por tipo e planejamento.',
    colunas: [
      { chave: 'semana', titulo: 'Semana', tipo: 'texto' },
      { chave: 'numeroResumo', titulo: 'Nº resumo', tipo: 'numero' },
      { chave: 'dataEmissao', titulo: 'Data emissão', tipo: 'data' },
      { chave: 'periodoInicio', titulo: 'Período início', tipo: 'data' },
      { chave: 'periodoFim', titulo: 'Período fim', tipo: 'data' },
      { chave: 'unidade', titulo: 'Unidade', tipo: 'texto' },
      { chave: 'produto', titulo: 'Produto/Material', tipo: 'texto' },
      { chave: 'pedidoLocal', titulo: 'Pedido/Local', tipo: 'texto' },
      { chave: 'qtdFabricada', titulo: 'Qtd. fabricada', tipo: 'numero' },
      { chave: 'ensaiosRealizados', titulo: 'Ensaios realizados', tipo: 'numero' },
      { chave: 'fissuras', titulo: 'Fissuras', tipo: 'numero' },
      { chave: 'vazios', titulo: 'Vazios', tipo: 'numero' },
      { chave: 'ombreiras', titulo: 'Ombreiras', tipo: 'numero' },
      { chave: 'quebras', titulo: 'Quebras', tipo: 'numero' },
      { chave: 'usp', titulo: 'USP', tipo: 'numero' },
      { chave: 'falhasFabricacao', titulo: 'Falhas fabricação', tipo: 'numero' },
      { chave: 'outros', titulo: 'Outros', tipo: 'numero' },
      { chave: 'totalRefugos', titulo: 'Total refugos', tipo: 'numero' },
      { chave: 'taxaRefugo', titulo: 'Taxa de refugo', tipo: 'numero' },
      { chave: 'ensaiosPorMil', titulo: 'Ensaios por 1.000', tipo: 'numero' },
      { chave: 'planejamentoInicio', titulo: 'Planejamento início', tipo: 'data' },
      { chave: 'planejamentoFim', titulo: 'Planejamento fim', tipo: 'data' },
      { chave: 'qtdPlanejada', titulo: 'Qtd. planejada', tipo: 'numero' },
    ],
  },
};

/** Ordem em que as abas aparecem na interface e no xlsx exportado. */
export const ORDEM_MODELOS = ['rastreabilidade', 'ensaios', 'resumo'];
